### ISSUE TITLE
A test randomely fails

### ISSUE THREAD

**Issue by sonnyp** [node-xmpp/node-expat#125]
![screen shot 2015-08-29 at 00 58 15](https://cloud.githubusercontent.com/assets/19673/9558711/2218186c-4de9-11e5-89d5-2b71f40c4540.png)

Hitting restart job on travis usually fixes it.

**Comment by tomhughes** [comment]
That's because the tolerance on the "stop and resume" test is too tight.

There are two 500ms delays created in the parse, and it expects the total parse time to be 1s +/- 10% but on slower machines it often takes more than 1.1s because of delays over and above the artificial ones.

So on the ARM machines in the Fedora build farm it typically takes around 1.3 or so (two runs I just did were 1318ms and 1323ms) while the i686 and x86_64 machines do finish in the allotted time.

I think a 10% margin on the minimum end is find (arguably no margin should be fine there are it should always take at least 1s in total) but on the maximum end it needs to be large, or not be checked at all, as you have no idea how long it might take over and above the artificial pauses.
